1558761315994	Sync.LogManager	DEBUG	Flushing file log
1558761316011	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557897316011
1558761316095	Sync.LogManager	DEBUG	Done deleting files.
1558761316169	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558761316169	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558761316172	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558761316960	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558761320187	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558761320187	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558761320193	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558761320193	Sync.Service	INFO	Starting sync at 2019-05-24 23:15:20 in browser session fq4s4dI8VdD-
1558761320194	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558761320198	Sync.Status	INFO	Resetting Status.
1558761320198	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558761320216	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558761320216	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558761320216	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558761320217	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558761320218	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558761320221	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
