1558639827081	Sync.LogManager	DEBUG	Flushing file log
1558639827086	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1558639827086	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2152398878
1558639827086	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1558639827086	Services.Common.RESTRequest	TRACE	GET body: 
1558639827087	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1558639827148	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557775827148
1558639827188	Sync.LogManager	DEBUG	Done deleting files.
1558639827976	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558639830082	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558639830083	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558639830088	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558639830088	Sync.Service	INFO	Starting sync at 2019-05-23 13:30:30 in browser session tHe9ZTGSpbz-
1558639830089	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558639830092	Sync.Status	INFO	Resetting Status.
1558639830092	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558639830093	Sync.BrowserIDManager	INFO	Getting keys
1558639830094	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1558639830094	FirefoxAccounts	DEBUG	enter getAssertion()
1558639830094	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1558639830095	FirefoxAccounts	DEBUG	getAssertionFromCert
1558639830096	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1558639830096	Sync.BrowserIDManager	DEBUG	Getting a token
1558639830097	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://token.services.mozilla.com/1.0/sync/1.5
1558639830097	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1558639830097	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1558639830097	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1558639830098	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1558639830105	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://token.services.mozilla.com/1.0/sync/1.5
1558639830105	Services.Common.RESTRequest	TRACE	Channel for GET https://token.services.mozilla.com/1.0/sync/1.5 returned status code 2152398878
1558639830105	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1558639830105	Services.Common.RESTRequest	TRACE	GET body: 
1558639830105	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:35:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:58:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:244:13
1558639830106	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1558639830106	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1558639830107	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:35:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:58:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:244:13
1558639830109	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1558639830116	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558639830116	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558639830116	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1558639830117	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558639830117	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558639830120	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
