1558672690467	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558672749850	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558672755309	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558672760584	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558672760584	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558672760588	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558672761584	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558672779880	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558672779881	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558672779884	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558672779884	Sync.Service	INFO	Starting sync at 2019-05-23 22:39:39 in browser session Igju9bUWkDxV
1558672779884	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558672779888	Sync.Status	INFO	Resetting Status.
1558672779888	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558672779914	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558672779914	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558672779914	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558672779914	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558672779915	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558672779921	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
